### ISSUE TITLE
Backspace does not work when launched in UXTerm

### ISSUE THREAD

**Issue by Phundrak** [little-dude/xi-tui#73] opened 2018-09-27 13:57 UTC
Just as the title says, the backspace does not work in xi-term when launched in UXTerm (urxvt, `rxvt-unicode`) on GNU/Linux (Arch Linux).
From `urxvt-help`:
```
urxvt --help
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
```

`xi-term` launched with `cargo run --release -- ~/test/test.cpp`
Both xi-core and syntect-plugin are installed and running.

I also tested xi-term in Gnome Terminal, and it ran without any issue, hence I suspect UXTerm to be the cause of this issue.

**Comment by patrickisgreene** [comment] 2018-09-27 15:07
I just Installed UXTerm on ubuntu 18.04 to give this a look. I'm just using a default config and have made no modifications.
```
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,pixbuf,XIM,frills,selectionscrolling,wheel,slipwheel,smart-resize,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
```
Strangly enough backspace seems to work as intended, however the syntax highlighting is janky. and the background is green. I think this has something to do with ubuntu's XDefaults but i'm not sure i'll keep looking
![xi-term-unicode-urxvt](https://user-images.githubusercontent.com/22763629/46154449-cc859b80-c23a-11e8-9e94-9be4770f3d37.png)

**Comment by patrickisgreene** [comment] 2018-10-02 03:08
After having time to look into this today, i realized something i should have checked earlier [rxvt-unicode](http://pod.tst.eu/http://cvs.schmorp.de/rxvt-unicode/doc/rxvt.1.pod#COLOURS_AND_GRAPHICS) doesn't have 'True Colour' support  witch xi-term requires. So this is a no op atleast for now

**Comment by ktomsic** [comment] 2018-10-05 03:05
It's possible your terminal's configured to send ^H (the ASCII "BS" / "BackSpace" character, 0x08). There's some info about it in the [rxvt-unicode faq](http://pod.tst.eu/http://cvs.schmorp.de/rxvt-unicode/doc/rxvt.7.pod#What_s_with_the_strange_Backspace_De). You should be able to see what character / sequence backspace sends by typing Ctrl-V then a backspace. Xi-term expects '^?' (the ASCII "DEL" = "delete" character, 0x7F), which seems to be the default.

I actually ran into this problem in gnome-terminal. For whatever reason, my gnome-terminal configuration is set to use ^H for backspace. I'm not really sure why, since it's not the default -- maybe something to do with vim? Vim seems to crop up a fair amount when searching for for information about whether backspace should be mapped to ^? or ^H.

Anyway, @bytebuddha (or anyone else), if you're interested in a tiny change (literally one line) that handles Ctrl-H as backspace, I can post a pull request.

**Comment by patrickisgreene** [comment] 2018-10-05 12:47
@ktomsic thanks for your input, I'd certainly be willing to accept a pull request for this.

**Comment by patrickisgreene** [comment] 2018-10-10 14:22
This should be fixed now @Phundrak can you confirm?

**Comment by Phundrak** [comment] 2018-10-10 16:43
Yes I do, no more issues when using backspace!

**Closed as completed** 2018-10-10 16:46 UTC
