### ISSUE TITLE
Compilation error: mio-uds --> mismatched types

### ISSUE THREAD

**Issue by ghost** [little-dude/xi-tui#53] opened 2018-03-01 14:56 UTC
```
$ cargo run --release -- README.md
   Compiling serde_yaml v0.7.3
   Compiling backtrace-sys v0.1.16
   Compiling serde_derive_internals v0.19.0
   Compiling mio-uds v0.6.4
error[E0308]: mismatched types
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-uds-0.6.4/src/datagram.rs:33:48
   |
33 |             try!(cvt(libc::bind(fd.fd(), addr, len)));
   |                                                ^^^ expected i32, found u32

error[E0308]: mismatched types
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-uds-0.6.4/src/listener.rs:37:48
   |
37 |             try!(cvt(libc::bind(fd.fd(), addr, len)));
   |                                                ^^^ expected i32, found u32

   Compiling backtrace v0.3.5
error: aborting due to 2 previous errors

error: Could not compile `mio-uds`.
warning: build failed, waiting for other jobs to finish...
```

**Comment by patrickisgreene** [comment] 2018-03-03 21:42
hmm What rustc and cargo version's are you using?

**Comment by ghost** [comment] 2018-03-04 03:08
```
$ dpkg-query --list | grep -e "rust" -e "cargo"
ii  cargo                  0.24.0-1     aarch64      Rust package manager
ii  rustc                  1.23.0-1     aarch64      A safe, concurrent, practical language.

$ cat sources.list.d/pointless.list
deb [trusted=yes] https://its-pointless.github.io/files/ termux extras

$ uname -a
Linux localhost 3.18.31-perf-gdedd3c8 #1 SMP PREEMPT Fri Aug 11 17:41:01 CST 2017 aarch64 Android
```

**Comment by patrickisgreene** [comment] 2018-03-04 03:59
I'm unable to reproduce this error and don't have much time to look for a solution :/. Just a quick look through mio and friends Issue's, it seem's to have had trouble in the past compiling for the aarch64-linux-android target the only thing i could think of is maybe update rustc & cargo.
I'm sorry i can't provide a better answer.

**Comment by little-dude** [comment] 2018-03-12 14:48
I'm going to close this since this is not really an issue with xi-term itself. @afsec you should open an issue on the [mio-uds repo](https://github.com/alexcrichton/mio-uds/issues).

**Closed as completed by little-dude** 2018-03-12 14:48 UTC
